language: python
services:
  - postgresql
python:
  - "3.6"
script:
  - python run.py
install:
  - pip install -r requirements.txt
  - psql -c "CREATE DATABASE travel;" -U postgres
  - psql -c "CREATE USER travel WITH PASSWORD 'travel';" -U postgres
  - psql -c "ALTER ROLE travel WITH CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE travel to travel;" -U postgres
  - alembic upgrade head